version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev

    env_file:
      - .env
    environment:
      - DEBUG=app:*
      - PORT=3000
    tty: true

    # ホスト側のポート:コンテナのポート
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ~/.ssh:/tmp/.ssh

    working_dir: /app
    command: npm run dev
